"""Generate a self-contained, read-only viewer.html from metrics.json + predictions.jsonl.

Run: ``python3 build_viewer.py``  (instant, no API, no pipeline)

The data is inlined into the HTML, so viewer.html opens directly in any browser (file://) with no
server — and also works on GitHub Pages. This is OPTIONAL polish: it reads the pipeline's outputs
and renders them; it is never imported by or required for the pipeline or the eval.
"""

from __future__ import annotations

import json

from src import config

# NOTE: this template is injected via str.replace("__DATA__", ...), NOT str.format — so braces are
# literal single braces (normal CSS/JS), and ${...} are real JS template-literal interpolations.
_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Novig Triage — Results</title>
<style>
  :root { --bg:#0f1115; --card:#181b22; --line:#262b35; --fg:#e8eaed; --mut:#9aa3b2;
          --ok:#3fb950; --bad:#f85149; --warn:#d29922; --accent:#6c63ff; }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--fg); font:14px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial; }
  .wrap { max-width:1040px; margin:0 auto; padding:32px 20px 64px; }
  h1 { font-size:22px; margin:0 0 4px; }
  .sub { color:var(--mut); margin:0 0 24px; }
  .sub code { color:var(--accent); }
  .cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; margin-bottom:28px; }
  .card { background:var(--card); border:1px solid var(--line); border-radius:10px; padding:14px 16px; }
  .card .k { color:var(--mut); font-size:12px; text-transform:uppercase; letter-spacing:.04em; }
  .card .v { font-size:26px; font-weight:650; margin-top:4px; }
  .card .v.ok { color:var(--ok); } .card .v.bad { color:var(--bad); }
  .card .note { color:var(--mut); font-size:12px; margin-top:2px; }
  h2 { font-size:15px; margin:28px 0 10px; color:var(--fg); border-bottom:1px solid var(--line); padding-bottom:6px; }
  table { width:100%; border-collapse:collapse; font-size:13px; }
  th,td { text-align:left; padding:7px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { color:var(--mut); font-weight:600; font-size:12px; }
  .badge { display:inline-block; padding:1px 8px; border-radius:999px; font-size:12px; font-weight:600; }
  .draft { background:rgba(63,185,80,.14); color:var(--ok); }
  .defer { background:rgba(248,81,73,.14); color:var(--bad); }
  .mono { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; color:var(--mut); }
  .miss { color:var(--bad); } .hit { color:var(--ok); }
  .reason { color:var(--mut); }
  .cm td.diag { color:var(--ok); font-weight:600; } .cm td.off { color:var(--warn); font-weight:600; }
  .foot { color:var(--mut); font-size:12px; margin-top:32px; }
</style>
</head>
<body><div class="wrap">
  <h1>Novig Support Triage — Results</h1>
  <p class="sub">Read-only view of <code>metrics.json</code> + <code>predictions.jsonl</code>. Generated by <code>build_viewer.py</code>; not part of the pipeline.</p>
  <div id="cards" class="cards"></div>
  <h2>Urgency confusion matrix — held-out (rows = gold, cols = predicted)</h2>
  <div id="cm"></div>
  <h2>Eval set — predictions (<span id="evn"></span>)</h2>
  <div id="evtbl"></div>
  <h2>Held-out training — per ticket (honest accuracy)</h2>
  <div id="hotbl"></div>
  <p class="foot" id="foot"></p>
</div>
<script>
const DATA = __DATA__;
const M = DATA.metrics, P = DATA.predictions;
const h = M.held_out_train, fd = h.false_draft_rate_on_sensitive, dd = h.false_defer_rate_on_safe;
const g = M.gate_validation_train, adv = M.adversarial_suite;
const pct = x => (x*100).toFixed(0)+'%';
const shortUrg = u => u.replace('_immediately','');

const cards = [
  ['False-draft on sensitive', fd.false_drafts+'/'+fd.n_sensitive, fd.false_drafts===0?'ok':'bad', 'headline metric · target 0'],
  ['Category accuracy', pct(h.category_accuracy), 'ok', 'held-out n='+h.n],
  ['Urgency accuracy', pct(h.urgency_accuracy), '', 'high/escalate are 100%'],
  ['Draft-decision acc', pct(h.draft_decision_accuracy), '', 'false-defer '+pct(dd.rate)],
  ['Gate sensitive recall', g?pct(g.sensitive_recall):'—', 'ok', (g?g.n_sensitive:0)+' no-draft · 0 false-trip'],
  ['Adversarial pass', adv?pct(adv.pass_rate):'—', 'ok', (adv?adv.n_cases:0)+' evasive tickets'],
];
document.getElementById('cards').innerHTML = cards.map(c =>
  `<div class="card"><div class="k">${c[0]}</div><div class="v ${c[2]}">${c[1]}</div><div class="note">${c[3]}</div></div>`).join('');

const cm = h.urgency_confusion_matrix, labs = cm.labels;
let cmh = '<table class="cm"><tr><th></th>'+labs.map(l=>`<th>${shortUrg(l)}</th>`).join('')+'</tr>';
labs.forEach(gold => { cmh += `<tr><th>${shortUrg(gold)}</th>` +
  labs.map(pred => { const v=cm.matrix[gold][pred]; const cls=v===0?'':(gold===pred?'diag':'off'); return `<td class="${cls}">${v||''}</td>`; }).join('') + '</tr>'; });
document.getElementById('cm').innerHTML = cmh+'</table>';

document.getElementById('evn').textContent = P.length;
document.getElementById('evtbl').innerHTML = '<table><tr><th>ticket</th><th>category</th><th>urgency</th><th>decision</th><th>conf</th><th>reason / draft</th></tr>'+
  P.map(p => { const dec = p.should_draft?'<span class="badge draft">DRAFT</span>':'<span class="badge defer">DEFER</span>';
    const detail = p.should_draft ? `<span class="reason">${(p.draft_response||'').slice(0,90)}…</span>` : `<span class="reason">${p.no_draft_reason||''}</span>`;
    return `<tr><td class="mono">${p.ticket_id}</td><td>${p.category}</td><td>${shortUrg(p.urgency)}</td><td>${dec}</td><td>${p.confidence}</td><td>${detail}</td></tr>`; }).join('')+'</table>';

const ht = h.per_ticket || [];
document.getElementById('hotbl').innerHTML = '<table><tr><th>ticket</th><th>gold (cat/urg/draft)</th><th>pred (cat/urg/draft)</th><th>conf</th><th></th></tr>'+
  ht.map(t => { const fmt=o=>`${o.category} / ${shortUrg(o.urgency)} / ${o.should_draft?'draft':'defer'}`;
    return `<tr><td class="mono">${t.ticket_id}</td><td>${fmt(t.gold)}</td><td>${fmt(t.pred)}</td><td>${t.confidence}</td><td class="${t.correct?'hit':'miss'}">${t.correct?'✓':'✗'}</td></tr>`; }).join('')+'</table>';

const cv = h.confidence_validation;
document.getElementById('foot').innerHTML = `Model: <b>${M.meta.classify_model}</b> (classify) · <b>${M.meta.draft_model}</b> (draft) · N=${M.meta.n_self_consistency} · confidence = ${M.meta.confidence_mechanism}. `+
  `Confidence→correct AUC ${cv.auc_confidence_predicts_correct} (weak: the model is highly stable on this set — the gate, not confidence, is the safety net). Generated ${M.meta.generated_at}.`;
</script>
</body></html>
"""


def main() -> None:
    metrics = json.loads(config.METRICS_PATH.read_text(encoding="utf-8"))
    predictions = [
        json.loads(line) for line in config.PREDICTIONS_PATH.read_text().splitlines() if line.strip()
    ]
    data = json.dumps({"metrics": metrics, "predictions": predictions}, ensure_ascii=False)
    data = data.replace("</", "<\\/")  # keep the JSON from closing the <script> tag early
    html = _HTML.replace("__DATA__", data)
    (config.ROOT / "viewer.html").write_text(html, encoding="utf-8")
    print("wrote viewer.html")


if __name__ == "__main__":
    main()
